### ISSUE TITLE
missing @angular/platform-browser-dynamic/testing in package.json

### ISSUE THREAD

**Issue by sheikalthaf** [vikerman/ivy-universal#1]
```
ERROR in E:\Angular\ivy\ivy-universal\src\test.ts
[tsl] ERROR in E:\Angular\ivy\ivy-universal\src\test.ts(8,8)
      TS2307: Cannot find module '@angular/platform-browser-dynamic/testing'.
```

getting this error on build

**Comment by vikerman** [comment]
Ah ok. Let me add it back. I think you should be ok if you use that package-lock.

Also this is using experimental Ivy nightly builds. So it is better to use the package-lock that I've tested with.
